# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np 

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print("dimension:", A.ndim)
print("shape:", A.shape)
print("size", A.size)
print("datatype:", A.dtype)

dimension: 2
shape: (3, 5)
size 15
datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
print("Elementwise subtraction: \n\n", B-C, "\n")
print("Elementwise multiplication: \n\n", B*C, "\n")
print("Matrix multiplication: \n\n", B@C)

Elementwise subtraction: 

 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]] 

Elementwise multiplication: 

 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]] 

Matrix multiplication: 

 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("Exponentiate each number elementwise: \n\n", np.exp(B), "\n")
print("Calculate the minimum value in the whole matrix:", np.min(B), "\n")
print("Calculcate the minimum value in each row:", np.min(B, axis=1), "\n")
print("Calculcate the minimum value in each column:", np.min(B, axis=0), "\n")
print("Find the index value for the minimum value in the whole matrix:", np.argmin(B), "\n")
print("Find the index value for the minimum value in each row:", np.argmin(B, axis=1), "\n")
print("Calculate the sum for all elements:", np.sum(B), "\n")
print("Calculate the mean for each column:", np.mean(B, axis =0), "\n")
print("Calculate the median for each column:", np.median(B, axis=0), "\n")

Exponentiate each number elementwise: 

 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 

Calculate the minimum value in the whole matrix: 1 

Calculcate the minimum value in each row: [1 4 7] 

Calculcate the minimum value in each column: [1 2 3] 

Find the index value for the minimum value in the whole matrix: 0 

Find the index value for the minimum value in each row: [0 0 0] 

Calculate the sum for all elements: 45 

Calculate the mean for each column: [4. 5. 6.] 

Calculate the median for each column: [4. 5. 6.] 



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [10]:
print("You take all the values on the provided index. It's the same as writing A[1, :]")

You take all the values on the provided index. It's the same as writing A[1, :]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [13]:
for i in A:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [15]:
print("A is a 1D array.")

A is a 1D array.


In [16]:
print("B is a 3D array. It has 2 blocks and 3 rows in each block. The -1 tells numpy to calculate how many elements in each row/how many columns are needed.")

B is a 3D array. It has 2 blocks and 3 rows in each block. The -1 tells numpy to calculate how many elements in each row/how many columns are needed.


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [17]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [18]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [19]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [20]:
def add_mult_matrices(a, b, operation):
    if not isinstance(a, np.ndarray) or not isinstance(b, np.ndarray):
        raise TypeError("Both inputs must be NumPy arrays.")
        
    if operation == "add":
        if a.shape != b.shape:
            raise ValueError("Addition requires the inputs to have the same shape.")
        return a + b

    if operation == "multiply":
        if not a.shape[1] == b.shape[0]:
            raise ValueError("Multiplication requires the number of columns in the first input to match the number of rows in the second.")

        return a @ b

    raise ValueError("No valid operation vas provided.")

In [21]:
A = np.array([[1,2], [5,6]])
B = np.array([[9,10],[13,15]])

print("Addition: \n\n", add_mult_matrices(A, B, "add"), "\n")
print("Multiplication: \n\n",  add_mult_matrices(A, B, "multiply"), "\n")

Addition: 

 [[10 12]
 [18 21]] 

Multiplication: 

 [[ 35  40]
 [123 140]] 



### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [ ]:
Uppgift: 10.1.1

x = (4,3)
(a) Vilken dimension har vektorn x: 2
(b) Beräna 5x: (20,15)
(c) Beräkna 3x: (12,9)
(d) Beräkna 5x + 3x: (32,24)
(e) Beräkna 8x: (32,24)
(f) Beräkna 4x − x: (12,9)
(g) Beräkna x⊤, vilken blir den nya dimensionen efter att transponeringen utförts: 1x2
(h) är x + x⊤ definierat: Nej. De har olika former.
(i) Beräkna ∥x∥: 5

Uppgift: 10.1.2

(a) Vilken dimension har vektorn v: 4x1
(b) Beräkna 2v: 6
                14
                0
                22
(c) Beräkna 5v + 2v: 21
                     49
                     0
                     77

(d) Beräkna 4v - 2v: Samma som B
(e) Beräkna v⊤, vilken blir den nya dimensionen efter att transponeringen utförts: 1x4
(f) Beräkna ∥v∥: 13,379

Uppgift 10.1.3

v1 = (4, 3, 1, 5)
v2 = (2, 3, 1, 1)
(a) Beräkna ∥v1∥: 7,1414
(b) Beräkna ∥v1 − v2∥: 4,4721


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [ ]:
Uppgift: 10.2.1

(a): [4 2 -2 
     2 -2 2]

(b): [0 -4 3
    0 -2 -4]

(c): Ej definerat.

(d): [3 2
    2 3]

(e): [9 12
    12 9]

(f): [-4 -4
      -4 -4]

(g): Ej definerat.

(h): Ej definerat.

(i): [11 10
    10 11]

(j): [8 -10 -3
      10 -8 0]

(k): [1 2
      2 1]

(l): [5 2
      7 4]

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [22]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [23]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [24]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
The .base call will reveille that v2 is a view. Changing the last element in V2 changes the V2 aswell since a view is a reference to V1.